[package]
name = "li-inference"
version = "0.1.0"
edition = "2024"

[dependencies]
li-core = { path = "../li-core", version = "0.1.0" }
li-model = { path = "../li-model", version = "0.1.0" }
li-workspace = { path = "../li-workspace", version = "0.1.0" }
li-factors = { path = "../li-factors", version = "0.1.0" }
