[package]
name = "benchmarks"
description = "LI-ESKG benchmarks."
edition = "2024"
version = "1.0.0"
publish = false

[dependencies]
# criterion = { version = "0.8", features = ["html_reports"] }
criterion = { version = "5.0.1", features = ["html_reports"], package = "codspeed-criterion-compat" }
bytes = "1.12"
petgraph = "0.8"
smallvec = "1.15"
thiserror = "2"

li-core = { path = "../crates/li-core" }
li-factors = { path = "../crates/li-factors" }
li-inference = { path = "../crates/li-inference" }
li-model = { path = "../crates/li-model" }
li-runtime = { path = "../crates/li-runtime" }
li-storage = { path = "../crates/li-storage", default-features = false }
li-workspace = { path = "../crates/li-workspace" }

[[bench]]
name = "invariant_benches"
harness = false

[[bench]]
name = "runtime_benches"
harness = false

[[bench]]
name = "workspace_bench"
harness = false

[[bench]]
name = "model_benches"
harness = false
