name: CI

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  style:
    name: Check style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Rust (Nightly)
        uses: moonrepo/setup-rust@v1
        with:
          channel: nightly  # because our formatting need nightly channel.
          components: rustfmt

      - name: Cargo fmt
        run: cargo fmt --check

  clippy:
    name: Run clippy
    needs: [style]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Rust
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          components: clippy

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: ${{ matrix.name }}
    needs: [clippy]
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux / stable
            os: ubuntu-latest
            rust: stable

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Rust
        uses: moonrepo/setup-rust@v1
        with:
          channel: ${{ matrix.rust }}

      - name: Build & Test
        run: cargo test --all-features --locked

  benchmark:
    name: Run benchmarks
    needs: [clippy]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Rust & cargo-codspeed
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          bins: cargo-codspeed

      - name: Build benchmarks
        run: cargo codspeed build

      - name: Run benchmarks with CodSpeed
        uses: CodSpeedHQ/action@v4
        with:
          run: cargo codspeed run
          mode: simulation
